# Generated by Django 3.2.7 on 2021-10-25 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 25, 22, 45, 51, 38067)),
        ),
    ]
