# Generated by Django 3.2.7 on 2021-11-25 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='General Practicioner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 25, 20, 41, 12, 695547)),
        ),
    ]
